allowBuilds:
  esbuild: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vite-plus: 0.2.5
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@0.2.5"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.2.5"
  - "@voidzero-dev/vite-plus-darwin-x64@0.2.5"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.5"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.2.5"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.2.5"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.2.5"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.5"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.2.5"
  - vite-plus@0.2.5
onlyBuiltDependencies: ["esbuild"]
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
trustPolicy: no-downgrade
trustPolicyExclude:
  - "@netlify/edge-bundler@14.10.3"
  - "@netlify/serverless-functions-api@2.16.0"
  - "@netlify/zip-it-and-ship-it@14.7.1"
  - "chokidar@4.0.3"
  - "semver@6.3.1"
