allowBuilds:
  esbuild: true
  netlify: true
  sharp: true
  unix-dgram: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0-rc.1
  vite-plus: 1.0.0-rc.1
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"
  - oxlint
  - "@oxlint/*"
  - "@oxc-project/*"
  - cn
  - "@shadcn/*"
  - oxlint-tsgolint
  - "@oxlint-tsgolint/*"
  - oxfmt
  - "@oxfmt/*"
  - vitest
  - "@vitest/*"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
trustPolicy: no-downgrade
trustPolicyExclude:
  - "@netlify/serverless-functions-api@2.18.0 || 2.22.0 || 2.23.0"
  - "chokidar@4.0.3"
  - "semver@6.3.1"
overrides:
  sharp@<0.35.4: ^0.35.4
  vite@*: "catalog:"
