import type { APIRoute } from "astro";

import { resources, siteUrl } from "@lib/resource-catalog";

const document = {
  openapi: "3.1.0",
  info: {
    title: "m4t.tf Site Resources",
    version: "0.1.0",
    description:
      "Machine-readable resources published by m4t.tf. API compatibility is identified with the required API-Version header. The current API version is 1. Deprecated resources will be marked with Deprecation and Sunset response headers and documented with their retirement timeline before removal.",
  },
  components: {
    parameters: {
      ApiVersion: {
        name: "API-Version",
        in: "header",
        required: true,
        description: "The API compatibility version requested by the client.",
        schema: { type: "integer", enum: [1] },
      },
    },
    schemas: {
      Problem: {
        type: "object",
        required: ["type", "title", "status", "detail", "code"],
        properties: {
          type: {
            type: "string",
            format: "uri-reference",
            description: "A URI identifying the problem type.",
          },
          title: {
            type: "string",
            description: "A short, human-readable summary of the problem.",
          },
          status: {
            type: "integer",
            description: "The HTTP status code generated by the origin server.",
          },
          detail: {
            type: "string",
            description: "A human-readable explanation specific to this occurrence.",
          },
          instance: {
            type: "string",
            format: "uri-reference",
            description: "A URI identifying the specific problem occurrence.",
          },
          code: {
            type: "string",
            description: "A stable machine-readable error code.",
          },
        },
      },
    },
    responses: {
      NotFound: {
        description: "The requested resource does not exist.",
        content: {
          "application/problem+json": {
            schema: { $ref: "#/components/schemas/Problem" },
            example: {
              type: "https://m4t.tf/problems/not-found",
              title: "Resource not found",
              status: 404,
              detail: "The requested resource does not exist.",
              code: "RESOURCE_NOT_FOUND",
            },
          },
        },
      },
      InternalServerError: {
        description: "The server encountered an unexpected condition.",
        content: {
          "application/problem+json": {
            schema: { $ref: "#/components/schemas/Problem" },
            example: {
              type: "https://m4t.tf/problems/internal-server-error",
              title: "Internal server error",
              status: 500,
              detail: "The server could not complete the request.",
              code: "INTERNAL_SERVER_ERROR",
            },
          },
        },
      },
    },
  },
  servers: [{ url: siteUrl }],
  paths: Object.fromEntries(
    resources.map((resource) => [
      resource.path,
      {
        get: {
          summary: resource.title,
          parameters: [{ $ref: "#/components/parameters/ApiVersion" }],
          responses: {
            "200": {
              description: resource.description,
              content: { [resource.type]: {} },
            },
            "404": { $ref: "#/components/responses/NotFound" },
            "500": { $ref: "#/components/responses/InternalServerError" },
          },
        },
      },
    ]),
  ),
} as const;

export const GET = (() =>
  Response.json(document, {
    headers: { "Content-Type": "application/vnd.oai.openapi+json;version=3.1" },
  })) satisfies APIRoute;
