import { siteUrl } from "@features/discovery/catalog";
import { appendVaryValue } from "@features/discovery/negotiation";

type Problem = {
  type: string;
  title: string;
  status: number;
  detail: string;
  code: string;
};

const problemCodes = ["RESOURCE_NOT_FOUND", "INTERNAL_SERVER_ERROR"] as const;

const notFoundProblem: Problem = {
  type: `${siteUrl}/problems/not-found`,
  title: "Resource not found",
  status: 404,
  detail: `No resource exists at the requested path. The published resources are listed at ${siteUrl}/llms.txt.`,
  code: "RESOURCE_NOT_FOUND",
};

const serverErrorProblem: Problem = {
  type: `${siteUrl}/problems/internal-server-error`,
  title: "Internal server error",
  status: 500,
  detail: "The server could not complete the request.",
  code: "INTERNAL_SERVER_ERROR",
};

export const problemSchema = {
  type: "object",
  required: ["type", "title", "status", "detail", "code"],
  properties: {
    type: {
      type: "string",
      format: "uri-reference",
      description: "A URI identifying the problem type.",
    },
    title: {
      type: "string",
      description: "A short, human-readable summary of the problem.",
    },
    status: {
      type: "integer",
      description: "The HTTP status code generated by the origin server.",
    },
    detail: {
      type: "string",
      description: "A human-readable explanation specific to this occurrence.",
    },
    instance: {
      type: "string",
      format: "uri-reference",
      description: "A URI identifying the specific problem occurrence.",
    },
    code: {
      type: "string",
      enum: [...problemCodes],
      description: "A stable machine-readable error code.",
    },
  },
};

export function problemResponse(
  response: Response,
  acceptsJson: boolean,
  pathname: string,
): Response {
  if (acceptsJson) {
    const problem = response.status === 404 ? notFoundProblem : serverErrorProblem;

    return new Response(JSON.stringify({ ...problem, instance: pathname }), {
      status: response.status,
      headers: {
        "Content-Type": "application/problem+json; charset=utf-8",
        Vary: "Accept",
      },
    });
  }

  const headers = new Headers(response.headers);
  appendVaryValue(headers, "Accept");

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}
