name: CI
on:
  push:
    branches: [main]
    tags: ["v*"]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: .node-version
      - run: vp i --frozen-lockfile
      - run: vp check
      - run: vp run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist-production
          path: dist
