name: CI
on:
  push:
    branches: [master]
    tags: ["v*"]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: .node-version
      - run: vp i --frozen-lockfile
      - run: vp check
      - run: vp run build
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          R2_BUCKET: ${{ secrets.R2_BUCKET }}
          R2_PUBLIC_URL: ${{ vars.R2_PUBLIC_URL }}
          PUBLIC_PREVIEW_BLOG: ${{ vars.PUBLIC_PREVIEW_BLOG }}
          PUBLIC_PREVIEW_PROJECTS: ${{ vars.PUBLIC_PREVIEW_PROJECTS }}
          PUBLIC_PREVIEW_PHOTOS: ${{ vars.PUBLIC_PREVIEW_PHOTOS }}
          PUBLIC_PREVIEW_VIGNETTES: ${{ vars.PUBLIC_PREVIEW_VIGNETTES }}
          PUBLIC_PREVIEW_GRAPHICS: ${{ vars.PUBLIC_PREVIEW_GRAPHICS }}
          PUBLIC_PREVIEW_MUSIC: ${{ vars.PUBLIC_PREVIEW_MUSIC }}
      - uses: actions/upload-artifact@v7
        with:
          name: dist-production
          path: dist
